### ISSUE TITLE
Change from Running Triplicate to Duplicate - Maybe Terence

### ISSUE THREAD

**Issue by tiddlek** [Hendricks-Laboratory/OT2Control#91]
**Hard coded into controller.py is the fact that we run each reaction three times to sort out any bad data**
Find where we can change this 3 to a 2. 

**Additionally there is a function scan_until_complete that should verify multiple data points are similar enough**
1. Can it do this with 2 or 3 or any number of data points?
2. Can we see a list of which dat frames it modifies

**Comment by TMahlatini** [comment]
1. From what I can understand, the function can handle comparisons between multiple data points because its loading a parameter row, which is likely an array of multiple data points. 
2. This function is likely being called somewhere else, and the callee is the one handling modification of data frames.  

I am not sure yet where this function is being referenced and I think that's where we need to make our modifications.
